<script setup lang="ts">
const { priority } = useReviewWorkflow()
const stats = [{ label: 'Awaiting review', value: '27', change: '+4 today', tone: 'green' }, { label: 'High attention', value: '04', change: '2 escalated', tone: 'red' }, { label: 'Needs evidence', value: '09', change: '34% of queue', tone: 'amber' }, { label: 'Median review time', value: '11m', change: '↓ 18% this week', tone: 'dark' }]
const queue = computed(() => priority.value)
</script>
<template>
  <div class="dashboard-page">
    <section class="hero-row"><div><p class="eyebrow">Tuesday · 18 August 2026</p><h1 class="display-title">Good morning, Samira<span>.</span></h1><p class="hero-copy">Here’s what needs a careful look today.</p></div><div class="hero-tools"><span class="system-status"><i /> All systems operational</span><NuxtLink to="/campaigns/urgent-medical" class="primary-btn">Open high-risk demo <span>↗</span></NuxtLink></div></section>
    <section class="metric-grid"><article v-for="stat in stats" :key="stat.label" class="metric-card"><div class="metric-top"><span>{{ stat.label }}</span><span class="metric-arrow">↗</span></div><strong :class="`metric-${stat.tone}`">{{ stat.value }}</strong><small>{{ stat.change }}</small></article></section>
    <section class="content-grid"><div class="queue-card panel"><div class="section-head"><div><p class="eyebrow">AI priority queue</p><h2>Cases needing attention</h2></div><NuxtLink to="/campaigns" class="text-link">View all cases <span>→</span></NuxtLink></div><div class="queue-head"><span>Campaign</span><span>Priority reason</span><span>Risk</span><span>Age</span></div><NuxtLink v-for="(campaign, index) in queue" :key="campaign.id" :to="`/campaigns/${campaign.id}`" class="queue-row"><div class="campaign-cell"><span class="rank">0{{ index + 1 }}</span><div><strong>{{ campaign.title }}</strong><small>{{ campaign.creator }} · {{ campaign.category }}</small></div></div><div class="reason"><span v-if="campaign.findings[0]">{{ campaign.findings[0].title }}</span><span v-else>Complete dossier · low urgency</span></div><span class="pill" :class="`risk-${campaign.risk}`">{{ campaign.risk }}</span><span class="age">{{ campaign.age }}</span></NuxtLink></div><aside class="signal-column"><div class="signal-card dark-card"><p class="eyebrow light">Portfolio radar</p><h2>A pattern worth a closer look</h2><p>3 cases share beneficiary evidence gaps. This is a prioritization signal, not an accusation.</p><NuxtLink to="/campaigns" class="light-link">Inspect cases <span>→</span></NuxtLink><div class="signal-orbit"><b>3</b><small>cases</small></div></div><div class="signal-card panel"><p class="eyebrow">Review principle</p><blockquote>“AI doesn’t decide who deserves trust. It helps reviewers see the evidence faster.”</blockquote><div class="quote-author"><span class="avatar">A</span><span>Amanah design principle</span></div></div></aside></section>
  </div>
</template>
